blank_issues_enabled: true
contact_links:
  - name: â“ SpÃ¸rgsmÃ¥l & Support
    url: https://stavox.dk/forums/forum/946-sp%C3%B8rgsm%C3%A5l-support/
    about: SpÃ¸rg andre medlemmer om hjÃ¦lp med dine problemer pÃ¥ vores forum
  - name: ğŸ” Sikkerhedsfejl
    url: https://github.com/SaimorIVS/Stavox-Issues/blob/master/SECURITY.md
    about: Rapporter sikkerhedsfejl i henhold til vores sikkerhedspolitik
